services:
  - type: web
    name: iran-tracker
    runtime: python
    repo: https://github.com/adigp4-alt/drrrd
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 main:app --bind 0.0.0.0:$PORT
